api:
  insecure: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: reverse-proxy

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

certificatesResolvers:
  mydnsjp:
    acme:
      dnsChallenge:
        provider: mydnsjp
      email: <email>
      storage: /etc/traefik/certificate/wildcard/acme.json
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
